name: Build
on:
  push:
    branches:
      - 'main'

  pull_request:
    branches:
      - '*'

  create:
    tags:
      - v*

jobs:
  build:
    name: 👷 Build
    runs-on: ubuntu-latest
    steps:
    - name: 🛑 Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: ⬇️ Check out
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: 🐋 Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PAT }} # `PAT` is a secret that contains your Personal Access Token with `write:packages` scope
    - name: 🐋 Build and push docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          ghcr.io/whitedr/test-app:${{ github.sha }}
    - name: 🚀 Ship artifact
      id: ship
      uses: gimlet-io/gimlet-artifact-shipper-action@v0.8.2
      with:
        DEPLOY: "true"
        ENV: "staging"
        APP: "test-app"
      env:
        GIMLET_SERVER: ${{ secrets.GIMLET_SERVER }}
        GIMLET_TOKEN: ${{ secrets.GIMLET_TOKEN }}
    - name: Artifact ID
      run: echo "Artifact ID is ${{ steps.ship.outputs.artifact-id }}"
